<a href="https://colab.research.google.com/github/unVeroz007/DIF62130_KELAS-B_25_2311532008/blob/main/Praktikum4/GaussiianNB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

In [2]:
dataset_dict = {
    'Rainfall': [0.0, 2.0, 7.0, 18.0, 3.0, 3.0, 0.0, 1.0, 0.0, 25.0, 0.0, 18.0, 9.0, 5.0, 0.0, 1.0, 7.0, 0.0, 0.0, 7.0, 5.0, 3.0, 0.0, 2.0, 0.0, 8.0, 4.0, 4.0],
    'Temperature': [29.4, 26.7, 28.3, 21.1, 20.0, 18.3, 17.8, 22.2, 20.6, 23.9, 23.9, 22.2, 27.2, 21.7, 27.2, 23.3, 24.4, 25.6, 27.8, 19.4, 29.4, 22.8, 31.1, 25.0, 26.1, 26.7, 18.9, 28.9],
    'Humidity': [85.0, 90.0, 78.0, 96.0, 80.0, 70.0, 65.0, 95.0, 70.0, 80.0, 70.0, 90.0, 75.0, 80.0, 88.0, 92.0, 85.0, 75.0, 92.0, 90.0, 85.0, 88.0, 65.0, 70.0, 60.0, 95.0, 70.0, 78.0],
    'WindSpeed': [2.1, 21.2, 1.5, 3.3, 2.0, 17.4, 14.9, 6.9, 2.7, 1.6, 30.3, 10.9, 3.0, 7.5, 10.3, 3.0, 3.9, 21.9, 2.6, 17.3, 9.6, 1.9, 16.0, 4.6, 3.2, 8.3, 3.2, 2.2],
    'Play': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(dataset_dict)
df.head()

Rainfall  Temperature  Humidity  WindSpeed Play
0       0.0         29.4      85.0        2.1   No
1       2.0         26.7      90.0       21.2   No
2       7.0         28.3      78.0        1.5  Yes
3      18.0         21.1      96.0        3.3  Yes
4       3.0         20.0      80.0        2.0  Yes

In [3]:
X, y = df.drop('Play', axis=1), df['Play']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, shuffle=False)
print(pd.concat([X_train, y_train], axis=1), end='\n\n')
print(pd.concat([X_test, y_test], axis=1))

    Rainfall  Temperature  Humidity  WindSpeed Play
0        0.0         29.4      85.0        2.1   No
1        2.0         26.7      90.0       21.2   No
2        7.0         28.3      78.0        1.5  Yes
3       18.0         21.1      96.0        3.3  Yes
4        3.0         20.0      80.0        2.0  Yes
5        3.0         18.3      70.0       17.4   No
6        0.0         17.8      65.0       14.9  Yes
7        1.0         22.2      95.0        6.9   No
8        0.0         20.6      70.0        2.7  Yes
9       25.0         23.9      80.0        1.6  Yes
10       0.0         23.9      70.0       30.3  Yes
11      18.0         22.2      90.0       10.9  Yes
12       9.0         27.2      75.0        3.0  Yes
13       5.0         21.7      80.0        7.5   No
14       0.0         27.2      88.0       10.3   No
15       1.0         23.3      92.0        3.0  Yes
16       7.0         24.4      85.0        3.9  Yes
17       0.0         25.6      75.0       21.9   No
18       0.0

In [6]:
from sklearn.preprocessing import PowerTransformer

pt = PowerTransformer(standardize=True)
X_train_Transformer = pt.fit_transform(X_train)
X_test_Transformer = pt.transform(X_test)
print(X_train_Transformer)

[[-1.12664679  1.70170305  0.31329077 -1.06372102]
 [ 0.05597219  0.87952169  0.88230332  1.34533274]
 [ 0.86716996  1.36597555 -0.45277799 -1.45338193]
 [ 1.43333755 -0.80381552  1.58840659 -0.52887309]
 [ 0.31508602 -1.13057488 -0.23760221 -1.12107835]
 [ 0.31508602 -1.63274871 -1.28303046  1.18531636]
 [-1.12664679 -1.77976256 -1.77644441  1.05270656]
 [-0.3427653  -0.47570144  1.46898652  0.30465822]
 [-1.12664679 -0.9525142  -1.28303046 -0.76627067]
 [ 1.6099061   0.03391302 -0.23760221 -1.37993965]
 [-1.12664679  0.03391302 -1.28303046  1.61012798]
 [ 1.43333755 -0.47570144  0.88230332  0.76671735]
 [ 1.02527709  1.03129394 -0.76988727 -0.64142374]
 [ 0.64971568 -0.62500825 -0.23760221  0.39259042]
 [-1.12664679  1.03129394  0.6525535   0.71225976]
 [-0.3427653  -0.14629167  1.11488006 -0.64142374]
 [ 0.86716996  0.18435986  0.31329077 -0.33327305]
 [-1.12664679  0.54642886 -0.76988727  1.37070938]
 [-1.12664679  1.21371571  1.11488006 -0.81103354]]


In [7]:
# Calculate prior probabilities for each class
prior_yes = y_train.value_counts()['Yes'] / len(y_train)
prior_no = y_train.value_counts()['No'] / len(y_train)

print(f"Prior probability for 'Yes': {prior_yes}")
print(f"Prior probability for 'No': {prior_no}")


Prior probability for 'Yes': 0.5789473684210527
Prior probability for 'No': 0.42105263157894735


In [9]:
def calculate_class_probabilities(X_train_transformed, y_train, features_names):
  classes = y_train.unique()
  equations = pd.DataFrame(index=classes, columns=features_names)
  for cls in classes:
    X_train = X_train_transformed[y_train == cls]
    mean = X_class.mean(axis=0)
    std = X_train.std()
    equations.loc[cls] = mean / std
  return equations