<a href="https://colab.research.google.com/github/unVeroz007/DIF62130_KELAS-B_25_2311532008/blob/main/Praktikum4/GaussiianNB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import library yang dibutuhkan

In [1]:
from sklearn.model_selection import train_test_split #Digunakan untuk membagi dataset menjadi data latih (training set) dan data uji (testing set).
from sklearn.metrics import accuracy_score #Digunakan untuk menghitung akurasi model.
import pandas as pd #Digunakan untuk mengelola data dalam bentuk tabel (DataFrame).
import numpy as np #Digunakan untuk operasi matematika dan array.

##Kode ini membuat dataset cuaca dalam bentuk DataFrame pandas dengan 5 kolom:

Rainfall → Curah hujan (mm)

Temperature → Suhu udara (°C)

Humidity → Kelembaban udara (%)

WindSpeed → Kecepatan angin (m/s)

Play → Keputusan bermain atau tidak (Yes/No)

In [2]:
#Membuat Data dalam Bentuk Dictionary
dataset_dict = {
    'Rainfall': [0.0, 2.0, 7.0, 18.0, 3.0, 3.0, 0.0, 1.0, 0.0, 25.0, 0.0, 18.0, 9.0, 5.0, 0.0, 1.0, 7.0, 0.0, 0.0, 7.0, 5.0, 3.0, 0.0, 2.0, 0.0, 8.0, 4.0, 4.0],
    'Temperature': [29.4, 26.7, 28.3, 21.1, 20.0, 18.3, 17.8, 22.2, 20.6, 23.9, 23.9, 22.2, 27.2, 21.7, 27.2, 23.3, 24.4, 25.6, 27.8, 19.4, 29.4, 22.8, 31.1, 25.0, 26.1, 26.7, 18.9, 28.9],
    'Humidity': [85.0, 90.0, 78.0, 96.0, 80.0, 70.0, 65.0, 95.0, 70.0, 80.0, 70.0, 90.0, 75.0, 80.0, 88.0, 92.0, 85.0, 75.0, 92.0, 90.0, 85.0, 88.0, 65.0, 70.0, 60.0, 95.0, 70.0, 78.0],
    'WindSpeed': [2.1, 21.2, 1.5, 3.3, 2.0, 17.4, 14.9, 6.9, 2.7, 1.6, 30.3, 10.9, 3.0, 7.5, 10.3, 3.0, 3.9, 21.9, 2.6, 17.3, 9.6, 1.9, 16.0, 4.6, 3.2, 8.3, 3.2, 2.2],
    'Play': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(dataset_dict) #Mengonversi Dictionary ke DataFrame
df.head() #Menampilkan 5 Data Pertama

Rainfall  Temperature  Humidity  WindSpeed Play
0       0.0         29.4      85.0        2.1   No
1       2.0         26.7      90.0       21.2   No
2       7.0         28.3      78.0        1.5  Yes
3      18.0         21.1      96.0        3.3  Yes
4       3.0         20.0      80.0        2.0  Yes

#Membagi dataset menjadi data latih (training set) dan data uji (testing set), lalu mencetak hasilnya.

##X, y = df.drop('Play', axis=1), df['Play']
df.drop('Play', axis=1) → Menghapus kolom "Play", sehingga X berisi semua fitur kecuali label.

df['Play'] → Mengambil kolom "Play" sebagai y (label/target yang ingin diprediksi).

##X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, shuffle=False)

train_size=0.7 → 70% data digunakan untuk pelatihan, 30% untuk pengujian.

shuffle=False → Data tidak diacak, sehingga urutan tetap sama seperti di dataset awal.

##Menampilkan Hasil Pembagian Data
pd.concat([X_train, y_train], axis=1)
→ Menggabungkan kembali X_train dan y_train agar tampil seperti dataset awal.

pd.concat([X_test, y_test], axis=1)
→ Menggabungkan kembali X_test dan y_test untuk melihat data uji.


In [3]:
X, y = df.drop('Play', axis=1), df['Play'] #Memisahkan Fitur (X) dan Label (y)

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, shuffle=False) #Membagi Data Menjadi Data Latih dan Data Uji
print(pd.concat([X_train, y_train], axis=1), end='\n\n') #Menampilkan Hasil Pembagian Data
print(pd.concat([X_test, y_test], axis=1))

    Rainfall  Temperature  Humidity  WindSpeed Play
0        0.0         29.4      85.0        2.1   No
1        2.0         26.7      90.0       21.2   No
2        7.0         28.3      78.0        1.5  Yes
3       18.0         21.1      96.0        3.3  Yes
4        3.0         20.0      80.0        2.0  Yes
5        3.0         18.3      70.0       17.4   No
6        0.0         17.8      65.0       14.9  Yes
7        1.0         22.2      95.0        6.9   No
8        0.0         20.6      70.0        2.7  Yes
9       25.0         23.9      80.0        1.6  Yes
10       0.0         23.9      70.0       30.3  Yes
11      18.0         22.2      90.0       10.9  Yes
12       9.0         27.2      75.0        3.0  Yes
13       5.0         21.7      80.0        7.5   No
14       0.0         27.2      88.0       10.3   No
15       1.0         23.3      92.0        3.0  Yes
16       7.0         24.4      85.0        3.9  Yes
17       0.0         25.6      75.0       21.9   No
18       0.0

#Menggunakan Power Transformation untuk menormalkan distribusi data pada X_train dan X_test agar lebih sesuai untuk model machine learning.

##Mengimpor PowerTransformer dari Scikit-learn
PowerTransformer digunakan untuk menstabilkan varians dan membuat data lebih mendekati distribusi normal.

Cocok untuk data dengan distribusi skewed (miring) atau memiliki skala yang bervariasi.

##Membuat Objek Power Transformer
pt = PowerTransformer(standardize=True)
PowerTransformer(standardize=True) → Selain melakukan transformasi, hasilnya juga distandardisasi agar memiliki mean 0 dan varians 1.

##Menerapkan Transformasi pada Data Latih
X_train_Transformer = pt.fit_transform(X_train)
fit_transform(X_train) digunakan untuk menyesuaikan PowerTransformer dengan data latih dan mentransformasikannya.

##Menerapkan Transformasi pada Data Uji
X_test_Transformer = pt.transform(X_test)
transform(X_test) → Menggunakan skala yang sama dari data latih untuk mentransformasikan data uji.

##Menampilkan Hasil Transformasi
print(X_train_Transformer)
Menampilkan hasil transformasi dalam bentuk array numpy.





In [4]:
from sklearn.preprocessing import PowerTransformer #Import library PowerTransformer yang digunakan untuk menstabilkan varians dan membuat data lebih mendekati distribusi normal.

pt = PowerTransformer(standardize=True) ##Membuat Objek Power Transformer
X_train_Transformer = pt.fit_transform(X_train) #Menerapkan Transformasi pada Data Latih
X_test_Transformer = pt.transform(X_test) #Menerapkan Transformasi pada Data Uji
print(X_train_Transformer) #Menampilkan Hasil Transformasi

[[-1.12664679  1.70170305  0.31329077 -1.06372102]
 [ 0.05597219  0.87952169  0.88230332  1.34533274]
 [ 0.86716996  1.36597555 -0.45277799 -1.45338193]
 [ 1.43333755 -0.80381552  1.58840659 -0.52887309]
 [ 0.31508602 -1.13057488 -0.23760221 -1.12107835]
 [ 0.31508602 -1.63274871 -1.28303046  1.18531636]
 [-1.12664679 -1.77976256 -1.77644441  1.05270656]
 [-0.3427653  -0.47570144  1.46898652  0.30465822]
 [-1.12664679 -0.9525142  -1.28303046 -0.76627067]
 [ 1.6099061   0.03391302 -0.23760221 -1.37993965]
 [-1.12664679  0.03391302 -1.28303046  1.61012798]
 [ 1.43333755 -0.47570144  0.88230332  0.76671735]
 [ 1.02527709  1.03129394 -0.76988727 -0.64142374]
 [ 0.64971568 -0.62500825 -0.23760221  0.39259042]
 [-1.12664679  1.03129394  0.6525535   0.71225976]
 [-0.3427653  -0.14629167  1.11488006 -0.64142374]
 [ 0.86716996  0.18435986  0.31329077 -0.33327305]
 [-1.12664679  0.54642886 -0.76988727  1.37070938]
 [-1.12664679  1.21371571  1.11488006 -0.81103354]]


#Menghitung probabilitas prior (prior probabilities) untuk masing-masing kelas dalam y_train, yang diperlukan dalam Naïve Bayes Classification.

##Menghitung Jumlah Sampel untuk Tiap Kelas
y_train.value_counts() → Menghitung jumlah kemunculan 'Yes' dan 'No' dalam data latih.

y_train.value_counts()['Yes'] → Mengambil jumlah sampel dengan label 'Yes'.

y_train.value_counts()['No'] → Mengambil jumlah sampel dengan label 'No'.

Dibagi dengan len(y_train) agar mendapatkan probabilitas prior untuk setiap kelas.

In [5]:
# Calculate prior probabilities for each class
#Menghitung Jumlah Sampel untuk Tiap Kelas
prior_yes = y_train.value_counts()['Yes'] / len(y_train)
prior_no = y_train.value_counts()['No'] / len(y_train)

#Menampilkan Probabilitas Prior kelas 'Yes' dan 'No' dalam dataset latih.
print(f"Prior probability for 'Yes': {prior_yes}")
print(f"Prior probability for 'No': {prior_no}")

Prior probability for 'Yes': 0.5789473684210527
Prior probability for 'No': 0.42105263157894735


In [6]:
def calculate_class_probabilities(X_train_transformed, y_train, feature_names):
    classes = y_train.unique()  # Mengambil semua kelas unik dalam y_train
    equations = pd.DataFrame(index=classes, columns=feature_names)  # Membuat DataFrame kosong

    for cls in classes:
        X_class = X_train_transformed[y_train == cls]  # Filter data latih berdasarkan kelas

        mean = X_class.mean(axis=0)  # Rata-rata tiap fitur dalam kelas
        std = X_class.std(axis=0)  # Standar deviasi tiap fitur dalam kelas

        # Simpan mean dan std dalam format distribusi Gaussian
        equations.loc[cls] = [f"N({m:.3f}, {s:.3f})" for m, s in zip(mean, std)]

    return equations

# Menghitung class probabilities
class_probabilities = calculate_class_probabilities(X_train_Transformer, y_train, X.columns)
print("\n📊 Class Probabilities:")
print(class_probabilities)


📊 Class Probabilities:
             Rainfall       Temperature          Humidity         WindSpeed
No   N(-0.479, 0.697)   N(0.330, 1.056)   N(0.268, 0.896)   N(0.430, 0.878)
Yes   N(0.348, 1.042)  N(-0.240, 0.883)  N(-0.195, 1.026)  N(-0.312, 0.967)


#Menghitung probabilitas suatu nilai (x) dalam distribusi Gaussian, berdasarkan mean (rata-rata) dan std (standar deviasi) dari data.

x → Nilai yang ingin dihitung probabilitasnya

mean → Rata-rata data

std → Standar deviasi data

In [15]:
def gaussian_probability(x, mean, std):
    """Menghitung probabilitas Gaussian untuk nilai x dengan mean dan std tertentu."""
    exponent = -((x - mean) ** 2 / (2 * (std ** 2))) #Menghitung eksponen dari rumus distribusi Gaussian
    return (1 / (std * np.sqrt(2 * np.pi))) * np.exp(exponent)

In [16]:
def calculate_likelihood(X_test_transformed, class_probabilities):
    #Konversi X_test_transformed ke DataFrame (jika masih berbentuk NumPy array)
    if isinstance(X_test_transformed, np.ndarray):
        X_test_transformed = pd.DataFrame(X_test_transformed, columns=class_probabilities.columns, index=range(X_test_transformed.shape[0]))
    #Membuat DataFrame Kosong untuk Menyimpan Likelihood, Setiap baris → mewakili satu data uji. Setiap kolom → mewakili kelas (misalnya "Yes" dan "No").
    likelihoods = pd.DataFrame(index=X_test_transformed.index, columns=class_probabilities.index)

    #Looping untuk Menghitung Likelihood, class_likelihood = np.ones(X_test_transformed.shape[0]), Inisialisasi likelihood awal dengan nilai 1 untuk setiap data uji. Ini karena dalam Naïve Bayes, semua probabilitas fitur dikalikan.
    for cls in class_probabilities.index:  # Loop setiap kelas ('Yes' atau 'No')
        class_likelihood = np.ones(X_test_transformed.shape[0])  # Inisialisasi likelihood dengan 1
        for feature in class_probabilities.columns:  # Looping untuk Setiap Fitur dan Menghitung Probabilitas Gaussian
            mean, std = map(float, class_probabilities.loc[cls, feature].strip("N()").split(", "))
            class_likelihood *= gaussian_probability(X_test_transformed[feature], mean, std)

        likelihoods[cls] = class_likelihood #Menyimpan Hasil Likelihood ke DataFrame

    return likelihoods #Mengembalikan DataFrame Likelihood

#Menghitung probabilitas posterior untuk setiap kelas dan membuat prediksi akhir menggunakan Naïve Bayes Gaussian.

posterior_yes → Probabilitas akhir bahwa data uji termasuk dalam kelas "Yes".

posterior_no → Probabilitas akhir bahwa data uji termasuk dalam kelas "No".

np.where(posterior_yes > posterior_no, 'Yes', 'No')

Jika posterior_yes lebih besar, prediksi = "Yes"

Jika posterior_no lebih besar, prediksi = "No"



In [17]:
def predict_class(likelihoods, prior_yes, prior_no):
    """Menghitung probabilitas posterior dan menentukan prediksi akhir."""
    #Menghitung probabilitas posterior untuk kelas "Yes" dan "No":
    posterior_yes = likelihoods['Yes'] * prior_yes
    posterior_no = likelihoods['No'] * prior_no

    predictions = np.where(posterior_yes > posterior_no, 'Yes', 'No')  # Pilih kelas dengan probabilitas lebih tinggi
    return predictions

#Menghitung prior probabilities
#Menghitung Probabilitas Prior
prior_yes = y_train.value_counts()['Yes'] / len(y_train)
prior_no = y_train.value_counts()['No'] / len(y_train)

#Menghitung likelihood
likelihoods = calculate_likelihood(X_test_Transformer, class_probabilities)

#Menghitung prediksi
predictions = predict_class(likelihoods, prior_yes, prior_no)

#Menampilkan hasil prediksi beserta label aslinya
print("\n📊 Final Predictions with Actual Labels:")
results = pd.DataFrame({'Actual': y_test.values, 'Predicted': predictions})
print(results.to_string(index=True))


📊 Final Predictions with Actual Labels:
  Actual Predicted
0     No       Yes
1    Yes        No
2    Yes       Yes
3    Yes        No
4    Yes       Yes
5    Yes       Yes
6    Yes       Yes
7     No       Yes
8    Yes       Yes
